Add multi-UDC support (#7)
* Add multi-UDC support

* Modify src/radxa-otgutils usage

* 修改服务Description

* 修改选项顺序，并处理非预期参数

* 去除多余dh_installsystemd参数

* 去除错误忽略

* 使用bash语法进行判断

* 添加flock

* 修复/var/run/adbd.pid为空的问题

* 修改flock粒度

* 修改configfs创建删除逻辑

* 修改configfs删除逻辑

* 修改 deinit configfs 逻辑

* 修改flock miaosh

* 替换 start-stop-daemon 选项 -m 为 --make-pidfile

* Apply suggestions from code review

Co-authored-by: ZHANG Yuntian <yt@radxa.com>

* 修改configfs_make调用位置

* 修改 configuration 字段

* 修改 function_stop，取消删除$UDC文件夹

* 注销 configfs 判断文件夹是否存在

* 格式化语法

* 复用 UDC 设置

* 缩短 sleep 时间

* 修正日志

* 更正判断文件夹路径

* 删除多余调试日志

* add_udc 改名为 enable_udc

---------

Co-authored-by: ZHANG Yuntian <yt@radxa.com>

diff --git a/src/radxa-otgutils b/src/radxa-otgutils
--- a/src/radxa-otgutils
+++ b/src/radxa-otgutils
@@ -1,11 +1,38 @@
 #!/bin/bash -e
 
+lock_udc()
+{
+    configfs_make
+    exec 100<"/sys/kernel/config/usb_gadget/$UDC"
+    flock 100
+}
+
+unlock_udc()
+{
+    exec 100<&-
+}
+
+enable_udc()
+{
+    if [[ -n $(cat "/sys/kernel/config/usb_gadget/$UDC/UDC") ]];
+    then
+        echo "" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
+    fi
+    echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
+}
+
+configfs_make()
+{
+    if [ ! -e "/sys/kernel/config/usb_gadget/$UDC" ];
+    then
+        modprobe libcomposite
+        mkdir -p "/sys/kernel/config/usb_gadget/$UDC"
+    fi
+}
+
 configfs_init()
 {
-    modprobe libcomposite
-
-    mkdir -p "/sys/kernel/config/usb_gadget/radxa-otgutils"
-    pushd "/sys/kernel/config/usb_gadget/radxa-otgutils"
+    pushd "/sys/kernel/config/usb_gadget/$UDC"
 
     echo "0x1d6b" > "idVendor"  # Linux Foundation
     echo "0x0104" > "idProduct" # Multifunction Composite Gadget
@@ -22,7 +49,7 @@ configfs_init()
 
     mkdir -p "configs/r.1/strings/0x409"
     echo "500" > "configs/r.1/MaxPower"
-    echo "adb" > "configs/r.1/strings/0x409/configuration"
+    echo "USB Composite Device" > "configs/r.1/strings/0x409/configuration"
 
     popd
 }
@@ -38,14 +65,14 @@ function_init()
             ;;
     esac
 
-    if [ ! -e "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET" ];
+    if [ ! -e "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET" ];
     then
-        mkdir -p "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET"
+        mkdir -p "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET"
     fi
 
-    if [ ! -e "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET" ];
+    if [ ! -e "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/$GADGET" ];
     then
-        ln -s "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET" "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET"
+        ln -s "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET" "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/$GADGET"
     fi
 }
 
@@ -60,19 +87,39 @@ function_stop()
             ;;
     esac
 
-    if [ -e "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET" ];
+    if [ -e "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/$GADGET" ];
     then
-        rm "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET"
+        rm "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/$GADGET"
     fi
 
-    if [ -e "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET" ];
+    if [ -e "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET" ];
     then
-        rmdir "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET"
+        rmdir "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET"
+    fi
+    if [ -n "$(find "/sys/kernel/config/usb_gadget/$UDC/functions" -maxdepth 0 -type d -empty)" ];
+    then
+        if [ -e "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/strings/0x409" ];
+        then
+            rmdir "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/strings/0x409"
+        fi
+
+        if [ -e "/sys/kernel/config/usb_gadget/$UDC/configs/r.1" ];
+        then
+            rmdir "/sys/kernel/config/usb_gadget/$UDC/configs/r.1"
+        fi
+
+        if [ -e "/sys/kernel/config/usb_gadget/$UDC/strings/0x409" ];
+        then
+            rmdir "/sys/kernel/config/usb_gadget/$UDC/strings/0x409"
+        fi
+    else
+        enable_udc
     fi
 }
 
 start()
 {
+    lock_udc
     configfs_init
     function_init
 
@@ -84,59 +131,64 @@ start()
                 mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
             fi
             export service_adb_tcp_port=5555
-            start-stop-daemon --start --oknodo --pidfile /var/run/adbd.pid --startas /usr/bin/adbd --background
-            sleep 1
+            start-stop-daemon --start --oknodo --make-pidfile --pidfile /var/run/adbd.pid --startas /usr/bin/adbd --background
+            sleep 0
             ;;
     esac
 
-    local UDC=
-    UDC="$(basename "$(find /sys/class/udc -maxdepth 1 -mindepth 1 | sort | head -1)")"
-    if [ -z "$UDC" ];
-    then
-        echo "No USB Device Controller was detected. Did you set your OTG port to host mode?"
-        exit 1
-    fi
-    echo "$UDC" > "/sys/kernel/config/usb_gadget/radxa-otgutils/UDC" || true
+    enable_udc
+    unlock_udc
 }
 
 stop()
 {
+    lock_udc
     function_stop
-
     case "$MODE" in
         adbd)
-            start-stop-daemon --stop --oknodo --pidfile /var/run/adbd.pid --retry 5
+            start-stop-daemon --stop --oknodo --pidfile /var/run/adbd.pid --remove-pidfile --retry 5
             umount /dev/usb-ffs/adb
             rmdir /dev/usb-ffs/adb
             rmdir /dev/usb-ffs
             ;;
     esac
+    unlock_udc
 }
 
-MODE=
+MODE=""
 case "$1" in
-    adbd|usbnet)
-        MODE="$1"
-        ;;
-    *)
-        echo "Unknown mode. Valid values are adbd or usbnet."
-        exit 1
-        ;;
+adbd|usbnet)
+    MODE="$1"
+    ;;
+*)
+    echo "Unknown mode. Valid values are adbd or usbnet."
+    echo "Usage: $0 <adbd|usbnet> <UDC> <start|stop|restart>"
+    exit 1
 esac
 
-case "$2" in
-    start)
-        start
-        ;;
-    stop)
-        stop
-        ;;
-    restart|reload)
-        stop
-        start
-        ;;
+UDC=""
+if [ -e "/sys/class/udc/$2" ];
+then
+    UDC="$2"
+else
+    echo "This UDC does not exist, you can turn on the OTG port Peripheral mode device tree overlay at rsetup and look in the /sys/class/udc directory for."
+    echo "Usage: $0 <adbd|usbnet> <UDC> <start|stop|restart>"
+    exit 1
+fi
+
+case "$3" in
+start)
+    start
+    ;;
+stop)
+    stop
+    ;;
+restart|reload)
+    stop
+    start
+    ;;
 *)
-    echo "Usage: $0 <adbd|usbnet> <start|stop|restart>"
+    echo "Usage: $0 <adbd|usbnet> <UDC> <start|stop|restart>"
     exit 1
 esac
 
